version: '3.8'
services:
  main-db:
    image: postgres:15
    container_name: itss-main-db
    environment:
      POSTGRES_DB: itss-1
      POSTGRES_USER: taduylam
      POSTGRES_PASSWORD: 1
    ports:
      - "5434:5432"
    volumes:
      - itss-main-db-data:/var/lib/postgresql/data

volumes:
  itss-main-db-data:
